package order

import (
	"context"

	omspb "github.com/kmlcnclk/kc-oms/common/api"
)

type CreateOrderHandler struct {
}

func NewCreateOrderHandler() *CreateOrderHandler {
	return &CreateOrderHandler{}
}

func (h *CreateOrderHandler) Handle(ctx context.Context, req *omspb.CreateOrderRequest) (*omspb.CreateOrderResponse, error) {
	// TODO: connect to the order service with grpc
	// Process the order creation logic here
	// For example, you can call a service to create the order

	return &omspb.CreateOrderResponse{
		// TODO: Replace with actual order ID and status, order id should be generated by the order service.
		//  and should be unique
		OrderId: "123456",
		Status:  "created",
	}, nil
}
